### ISSUE TITLE
Fragment.getContext vs Application.getContext

### ISSUE THREAD

**Issue by AngleV** [bumptech/glide#1038]
I'm using the following code

```java
Glide.with(fragment.getContext())
```
to display hundred of photos using a LinearLayoutManager.
Scrolling is choppy jitter and laggy after a few scrolls.

But if i change the context to application context.

```java
public class myApp extends Application {

    private static Context context;

    public static Context getContext() {
        return context;
    }

    @Override
    public void onCreate() {
        super.onCreate();

        context = getApplicationContext();

```

and i use like this 

```java
Glide.with(myApp.getContext())
```

then scroll is fast smooth and everything works nice. However each time i scroll back images are blank and glide loads them again.

Why is this happening ???

**Comment by TWiStErRob** [comment]
How do you load the images, and what is your adapter and layout like? There shouldn't be any difference here, and in general I would say use `with(fragment)`, since you already have that nearby.

**Comment by TWiStErRob** [comment]
Also you should enable logging to see cache hits and misses, that bears a lot of info as to why it's slow.

**Comment by AngleV** [comment]
Images are coming from my model using a getter to grab the url. 

My adapter its a classic adapter with the viewholder pattern implementation. As for the layout its quite simple with a few views and tried hard to make it as shallow and wide as it gets.
Any advise how to enable logging.
I'm struggling with this issue for almost half month now and the whole app stayed behind in schedule

**Comment by TWiStErRob** [comment]
https://github.com/bumptech/glide/wiki/Debugging-and-Error-Handling

What's after Glide.with?

**Comment by AngleV** [comment]
thanks..

that is

```
                    .load(mItems.get(position).getImageSrc(mScreenWidth))
                    .override(mScreenWidth,mItems.get(position).getHeight())
                    .placeholder(new ColorDrawable(mContext.getResources().getColor(R.color.light_gray)))
                    .crossFade()
                    .diskCacheStrategy(DiskCacheStrategy.RESULT)
                    .listener(new RequestListener<String, GlideDrawable>() {
                        @Override
                        public boolean onException(Exception e, String model, Target<GlideDrawable> target, boolean isFirstResource) {
                            return false;
                        }

                        @Override
                        public boolean onResourceReady(GlideDrawable resource, String model, Target<GlideDrawable> target, boolean isFromMemoryCache, boolean isFirstResource) {
                            Utils.fadeOut(loadingView);   // hide progressbar
                            if (android.os.Build.VERSION.SDK_INT >= 21){
                                    String transition = Constants.TRANS_NAME + getAdapterPosition();
                                    mImageView.setTransitionName(beach_transition);
                            }

                            return false;
                        }
                    })
                    .into(mImageView);
```

**Comment by TWiStErRob** [comment]
The fact that changing the context helps this is really weird... I don't know what to do with that.

I think you should try re-building this structure without any fancy stuff first (e.g. `loadingView` and `placeholder`) and see when which part could make a difference.

---

*This is a really long shot without knowing anything more about your code and situation, but may worth a look*: Layout may be a problem too, even though everything is fixed size (i.e. doesn't change between loads) it's possible that the display is really choppy. I had that once and this is what I concluded:
> I didn't set a placeholder so on every line scroll it had to do a full layout because onLoadStarted(placeholder=null) cleared the imageview and invalidated the whole thing.
> So the solution: for fixed sized image views to perform fast enough we need to set an exact sized placeholder image, so when the real image is loaded the layout doesn't change.

and this is how I solved it:
```java
public class RigidImageView extends ImageView {
	public RigidImageView(Context context) { super(context); }
	public RigidImageView(Context context, AttributeSet attrs) { super(context, attrs); }
	public RigidImageView(Context context, AttributeSet attrs, int defStyleAttr) { super(context, attrs, defStyleAttr); }

	private boolean eatRequestLayout = false;
	@Override public void setImageDrawable(Drawable drawable) {
		eatRequestLayout = true;
		super.setImageDrawable(drawable);
		eatRequestLayout = false;
	}

	@Override public void requestLayout() {
		if (!eatRequestLayout) {
			super.requestLayout();
		}
	}

	// Calls through to setImageDrawable since Eclair
	@Override public void setImageBitmap(Bitmap bm) { super.setImageBitmap(bm); }
	@Override public void setImageResource(int resId) { throw new UnsupportedOperationException("Use setImageDrawable"); }
	@Override public void setImageURI(Uri uri) { throw new UnsupportedOperationException("Use setImageDrawable"); }
}
```
With this view the first layout determines the size and it stay that size until the layout around it doesn't change. Different sized drawables won't affect the size.

**Comment by AngleV** [comment]
@TWiStErRob 

I tried everything.
Removed placeholder removed crossfade removed loadingviews. Nothing works.
Scroll remains choppy. Using Application Context choppy goes away. BUT images are not there when scrolling back. Glide reloads them again.
I must say that each image has different height. And i keep the aspect ratio by using 

```
            mImageView.setLayoutParams(new FrameLayout.LayoutParams(
                    FrameLayout.LayoutParams.MATCH_PARENT,
                    (int) (mScreenWidth / mItems.get(position).getRatio())));
          Glide.with(.....
```

Honestly dont know if this has something to do.

Also i tried your RigidImageView class.. same thing. with fragment context is choppy. with app's context super fast smooth but i got the issue with reloading images.

**Comment by TWiStErRob** [comment]
So now you solved the context mistery, but have a choppy scroll all the time?

Try to pause on fling and resume at other events.
But use the same context you use for loading the image.

Are you running your app in debug mode? (i.e. debugger attached, it doesn't matter if compiled debuggable)

Changing the size of an image view invalidates all parents, which means that all the other views in the list will be laid out again and again when the list is doing its layout.

**Comment by AngleV** [comment]
@TWiStErRob 

Yes choppy scroll still exists.

Cant find what constant to should i use for fling.  any idea ?

Yes app is running in debug mode. But i tried in release mode and with the debugger de -attached. Same thing.

_Changing the size of an image view invalidates all parents, which means that all the other views in the list will be laid out again and again when the list is doing its layout._

How to overcome this ?

**Comment by TWiStErRob** [comment]
Don't change the size... sadly. Fixed height + centerCrop maybe? I guess this is not viable.

It looks like people are still using the old constants, but I'm not sure it works: https://gist.github.com/lauw/fc84f7d04f8c54e56d56, try it. There also seems to be a fling method: http://stackoverflow.com/a/29020256/253468 tbh I didn't need these before.

**Comment by TWiStErRob** [comment]
@sjudd, do you have anything that may help him?

**Comment by TWiStErRob** [comment]
Take a look at https://github.com/TWiStErRob/glide-support/commit/a1572179430e837d8410cc9f915d7c4737e584dd

**Comment by sjudd** [comment]
There are lots of reasons why scrolling may or may not be janky. You're going to need to investigate yourself. For a primer on some of the tools Android offers, consider: 

http://www.curious-creature.com/2012/12/01/android-performance-case-study/
http://www.curious-creature.com/2015/03/25/android-performance-case-study-follow-up/

If you can narrow it down to a particular problem in Glide, I'm happy to try to provide more insight on the options you have available. It's unlikely that we're going to find a cause by guessing. The only other issue I've come across that is general (most issues are app specific) is that loading large Bitmaps can be janky. If that's the issue, you could try using ``override()`` to set a very small image size and see if that gets rid of the jank.

**Comment by TWiStErRob** [comment]
Considering we're pretty far from the original issue, the Staggered example I wrote, and Sam's excellent performance pointers I think could be closed. Feel free to open new issues for specific problems.
