### ISSUE TITLE
You cannot start a load for a destroyed activity

### ISSUE THREAD

**Issue by huzhenjie** [bumptech/glide#1484]
My glide version:

`compile 'com.github.bumptech.glide:glide:3.7.0'`

# Exception info

```
java.lang.IllegalArgumentException: You cannot start a load for a destroyed activity
   at com.bumptech.glide.manager.RequestManagerRetriever.assertNotDestroyed(RequestManagerRetriever.java:134)
   at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:102)
   at com.bumptech.glide.Glide.with(Glide.java:653)
```

**Comment by TWiStErRob** [comment]
Yes? You cannot start a load for a destroyed activity. There's no better way of saying it. If the activity is destroyed it won't ever be visible again, the user can't see your image, so there's no point in even trying to start to download it. See #803 for more discussion.

**Comment by shivangbtech** [comment]
Getting Same Problem.

**Comment by tikkat3** [comment]
.... crash , why not log ?

**Comment by AAverin** [comment]
Same problem. Why is it a crash and not just log message?

**Comment by pankaj89** [comment]
I got the same problem, how to stop this crash? i am using gradle 'com.github.bumptech.glide:glide:3.7.0'

**Comment by steve111MV** [comment]
Hi @all. the problem occurs most when your activity is recreated and the context that's in Glide is an old one. for instance when you you have a CustomAdapter(ArrayList list, Context context), and in MainActivity or Fragment recreation, you're not passing the new context to the adapter. Glide then tells you that the context i'm using does no more exist. I hope you understood that. who ever needs a debug can invite me to contribute in his project.

**Comment by Emeritus-DarranKelinske** [comment]
What is a workaround for this issue?

**Comment by neonwarge04** [comment]
This annoying, as always, my app has so much callback lying around. They get triggered when some events occurred. They don't finished instantaneously so after some x ms they gonna call the callback method. The problem is the "in between" instances where the user gets out of the context (closed activity, fragment etc.) when the callback returns. You placed `load` method to do stuff asynchronously but we don't have  a way to stop this train wreck. Go lecture us on bad coding habits but look at my use case first and see this maybe a valid one:

Here is whats happening on my code:
1.) User opens the activity
2.) I query some info from the server using Retrofit(this may take a while esp if you have a shitty internet in the middle of Afghan desert) try it, its very reproducible
3.) Retrofit (after 1 hour), returns and says "HEY I AM DONE FETCHING YOUR DATA", its going to do what I ever the hell I ask it to in the callback I assigned to it. 
4.) Little to the app's awareness, the activity has been already closed! (But the app still open)
5.) Glide detects the activity is dead (as mentioned here) and happily crashed the app.

Luckily, retrofit is has a method dedicated for this. We can always call `cancel` on the enqueued Retrofit call in `onPause`, `onDestroy`, 'onStop`, (where ever it make sense to call this), I called mine in `onPause`. I also call `clear` on the target ImageView. 

    @Override
    public void onPause()
    {
        super.onPause();

        if(mGetRaffleCall != null) mGetRaffleCall.cancel();
        if(mGetRafflePrizeCall != null) mGetRafflePrizeCall.cancel();

        Glide.clear(mImageViewPreviousRaffle);
    }


Occasionally it still crashes. What do you Glide people suggest to do from here?

**Comment by Emeritus-DarranKelinske** [comment]
I fixed this by using getApplicationContext()

**Comment by steve111MV** [comment]
It's dangerous to load images with App context, the won't be recycled when
the activity dies
Le 6 avr. 2017 1:06 PM, "Darran Kelinske" <notifications@github.com> a
écrit :

**Comment by Emeritus-DarranKelinske** [comment]
Can you please provide an effective alternative then?

**Comment by steve111MV** [comment]
use the ViewHolder context.

Glide.with(holder.itemView.getContext())
.load(URL)
...

This is what i use to avoid IllegalStateException
Le 6 avr. 2017 1:13 PM, "Darran Kelinske" <notifications@github.com> a
écrit :

**Comment by TWiStErRob** [comment]
Guys, read the duplicate issue; particularly: [Dec 10-14](https://github.com/bumptech/glide/issues/803#issuecomment-163528497)

**Comment by Emeritus-DarranKelinske** [comment]
Will check it out. Thank you! :)

**Comment by guilmarc** [comment]
Got the same issue today when using version compiled into FirebaseUI v.2.0.1.  I was scrolling my recyclerview and error occurs.

**Comment by mohammadreza** [comment]
It can be fix by using:
```
if (!YourActivity.this.isFinishing()) {
Glide.with(...
}
```

**Comment by taranjeetsapra** [comment]
I fixed this using getApplicationContext() while initializing the glide as **Glide.with(getApplicationContext())** and pause all request by overriding onDestroy() as
 **@Override
    protected void onDestroy() {
        super.onDestroy();
        Glide.with(getApplicationContext()).pauseRequests();
    }**

**Comment by SharkyLV** [comment]
taranjeetspra, it will blocking pause all Glide requests - if you use a service that fires notifications and it uses Glide for the avatar - it will block the notification.

**Comment by meikaiss** [comment]
@targetapi(Build.VERSION_CODES.JELLY_BEAN_MR1)
private static boolean isActivityDestroyed(Activity activity) {
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR1
&& activity != null && activity.isDestroyed()) {
return true;
}
return false;
}

when you load image in Activity, please check like this. If the activity isDestroyed, stop load image by Glide， else load image by Glide

**Comment by sreejithraman** [comment]
@meikaiss
I tried doing what you did but I am still seeing the issue

**Comment by farhan** [comment]
I am using following util function before loading any image
```

if (isValidContextForGlide(getContext()) {
      // Load image via Glide lib.
}

 public static boolean isValidContextForGlide(final Context context) {
        if (context == null) {
            return false;
        }
        if (context instanceof Activity) {
            final Activity activity = (Activity) context;
            if (activity.isDestroyed() || activity.isFinishing()) {
                return false;
            }
        }
        return true;
    }
```

**Comment by sreejithraman** [comment]
@farhan yup, that's what i had to end up doing. should have updated it here.

**Comment by pulkitrathi17** [comment]
Use `Glide.with(getApplicationContext()` instead of `Glide.with(YourActivity.this)`
OR
if you are using an adapter or class  that does not extend Context or its sub-classes (Activity, etc) 
use `Glide.with(mContext.getApplicationContext()` where mContext is the context passed to the class.

**Comment by TWiStErRob** [comment]
@Emeritus-DarranKelinske @mohammadreza @taranjeetsapra @meikaiss @sreejithraman @farhan @pulkitrathi17 please don't use Application context, see https://stackoverflow.com/a/32887693/253468 and conversation around https://github.com/bumptech/glide/issues/803#issuecomment-163880203.

Pass the `RequestManager` into the adapter, or save it in a field with the closest possible context (potentially a fragment, or even a view). This way there's no need for checking, no global loads (easy leaks), testable, etc.

**Comment by TWiStErRob** [comment]
It's much less hacky than using app-context. It actually uses Glide's feature that it doesn't queue requests on paused request managers. It also encourages proper dependency injection. (e.g. you could simply do `@Inject RequestManager glide;` to hide the static call).

Re Picasso and earlier versions, not sure, I started using Glide 3.x and over only. A quick look at http://square.github.io/picasso/2.x/picasso/com/squareup/picasso/Picasso.html#with-android.content.Context- tells me that it returns "The global default Picasso instance." which means Picasso only has the equivalent of `Glide.with(applicationContext)`, so obviously this is a non-issue there.

**Comment by goonerDroid** [comment]
As mentioned by @farhan , I am using 

`Context glideContext = isValidContextForGlide(getContext())? getContext() : mActivity.getApplicationContext();`

and I am accessing mActivity in Fragment.Hence `mActivity.getApplicationContext();`

**Comment by onepiecepura** [comment]
I solve it by
Implement onDestroy LifecycleListener in RequestManager 

 private val requestManager by lazy { Glide.with(this) }

override fun onDestroy() {
        super.onDestroy()
        requestManager.onDestroy()
}

use -> requestManager.load().into()

**Comment by korchix** [comment]
i resolved it using this code `android:configChanges="orientation|screenSize"` in the AndroidManifext.xml of the destroyed Activity .

```
<activity
            android:name=".MainActivity"
            android:configChanges="orientation|screenSize"/>
```

**Comment by AhmadullahSaikat** [comment]
Please use `Glide.with(getApplicationContext())` instead of `Glide.with(this)`

**Comment by TWiStErRob** [comment]
Please don't use application context, use `Glide.with(this)` in `onCreate `to get the best context for resource management and use dependency injection to pass the `RequestManager` around. You don't even need to check for dying activities and stuff. See https://stackoverflow.com/a/32887693

**Comment by houchenl** [comment]
`public static void loadUrl(Context context, String url) {
        if (ContextUtil.isDestroyed(context)) {
            // 避免在activity销毁后仍加载显示图片
            return;
        }

        Glide.with(context)
                .load(url)
                .downloadOnly(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL);
    }`

`public static boolean isDestroyed(Context context) {
        if (null == context) {
            return true;
        }

        if (context instanceof Activity) {
            Activity activity = (Activity) context;

            if (activity.isFinishing()) {
                return true;
            }

            return Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR1 && activity.isDestroyed();
        }

        return false;
    }`

**Comment by houchenl** [comment]
`
public static void loadUrl(Context context, String url) {
        if (ContextUtil.isDestroyed(context)) {
            // 避免在activity销毁后仍加载显示图片
            return;
        }

        Glide.with(context)
                .load(url)
                .downloadOnly(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL);
    }
`

`
public static boolean isDestroyed(Context context) {
        if (null == context) {
            return true;
        }

        if (context instanceof Activity) {
            Activity activity = (Activity) context;

            if (activity.isFinishing()) {
                return true;
            }

            return Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR1 && activity.isDestroyed();
        }

        return false;
    }
`

**Comment by plokijuhyg** [comment]
goto link:
[https://github.com/bumptech/glide/issues/1104](url)
