### ISSUE TITLE
Doc : Update the configuration part about cache as it's deprecated

### ISSUE THREAD

**Issue by Tolriq** [bumptech/glide#409]
Documentation (Wiki) about configuration of cache shows deprecated ways of configuring.

The correct way seems to be to use a factory and only InternalCacheDiskCacheFactory is provided by default.

But InternalCacheDiskCacheFactory as it's name implies only allow internal path while previous way did allow custom directory on sdcard for example.

Do you want a PR that adds a CustomCacheDiskCacheFactory that handle this or maybe the InternalCacheDiskCacheFactory should be made more generic ?

**Comment by TWiStErRob** [comment]
The deprecated doc only says to use the overloaded variant of the method, from there you're free to implement the `DiskCache.Factory` interface however you want. The most trivial way is to return the diskCache you would have used before the deprecation (as is done by the deprecated method). You can use `DiskLruCacheWrapper.get()` to simplify, but beware it currently behaves as a singleton which is fine in most cases. Here's what I used when needed an external cache: https://gist.github.com/TWiStErRob/d8da8038fc85d6363ad8

**Comment by Tolriq** [comment]
Well yes I know and I have implemented it :) But it's better to have a doc that do not say to use deprecated things :)

And if possible that no function are lost without having to code them.

But only my point of view.

**Comment by TWiStErRob** [comment]
Aaaaah, I just realized when you say documentation, you mean the [wiki](https://github.com/bumptech/glide/wiki/Configuration#disk-cache) not the [Javadoc](https://github.com/bumptech/glide/blob/v3.5.2/library/src/main/java/com/bumptech/glide/GlideBuilder.java#L73) :). All clear now.

By the way, I agree having more free to use utility classes, but I also agree that it's more maintenance for @sam, who is the only developer here currently as far as I know.

**Comment by sjudd** [comment]
I wouldn't at all mind a PR that makes the existing factory more generic or that adds an additional factory or two (or both) to make it easier to change the location. Like most of the feature requests we get, that hasn't happened not because I think it's a bad idea, but because no one has sent me a PR yet :).

**Comment by sjudd** [comment]
Also I updated the documentation, let me know if you think it needs further changes and thanks for pointing this out.

**Comment by Tolriq** [comment]
New doc is quite clear, and provide an easy way to provide externalCache.

I'll see in future (far) to make PR to improve default factory or add a new one, but I'm now focused and seeing if I all works I can migrate to glide :)

For the moment without using the dual Glide load that locks all seems to work. Was just facing a strange bug of Android on some devices (Nexus 9 : a cancel from Glide that will stop network transfer will not trigger an exception in BitmapFactory.decodeStream and it will result in an half loaded image but perfectly valid. It's important to check that there was no cancel before supposing the bitmap is ok)

Maybe it was the problem one other user reported about half loaded images.

**Comment by sjudd** [comment]
@Tolriq That sounds worth of reporting as a new issue if you can reproduce it. We don't currently cancel network requests (only before the request starts) in most cases.

**Comment by Tolriq** [comment]
Well it's was a problem with my code, was just reporting in case it could happens with Glide natively (but never saw)

But you do cancel requests : 

in ```DataFetcher<InputStream> ``` ```    public InputStream loadData(Priority priority) throws Exception {```

If I do download an image with BitmapFactory.decodeStream it will be cancelled when scrolling the list/grid view.

And ```public void cancel() {``` is correctly called just before it happens.

I just set an AtomicBoolean to true in on cancel then after the decodeStream return just check is it's set. In that case it was a cancel and bitmap have 90% chance to be invalid so I drop it.

Works perfectly so far on all devices.

**Comment by sjudd** [comment]
Ahh ok I see what you mean.

Yes we do cancel requests. But if you look at the implementations of DataFetcher that do network operations using streams ([HttpUrlFetcher][1], [OkHttpFetcher][2]), we typically don't implement cancel, or if we do, we only cancel between individual requests. This explains why we don't typically see the issue you describe, but you might if you implement cancel yourself.

I think your point is valid, we should ignore data we get back from cancelled requests because it might contain partial data. There is also a framework bug to avoid the partial decode failure (the API provides no way to distinguish between a partial and a full decode). I believe it has actually been fixed in L, but I haven't tested it.

[1]: https://github.com/bumptech/glide/blob/master/library/src/main/java/com/bumptech/glide/load/data/HttpUrlFetcher.java#L115
[2]: https://github.com/bumptech/glide/blob/master/integration/okhttp/src/main/java/com/bumptech/glide/integration/okhttp/OkHttpStreamFetcher.java#L76

**Comment by Tolriq** [comment]
Well this is strange

My cancel code only contains : 

```
    @Override
    public void cancel() {
        mIsCancelled.set(true);
        // TODO: call cancel on the client when this method is called on a background thread. See #257
    }
```

And yet there's cancellation, maybe the problem rely in the cleanup code that close the stream so will obviously stop the current decodeStream if the loadData is not blocking.

And the closure of the stream that return half images without triggering exception is still present in Android 5.1 of the Nexus 9.
